name: altar_of_prayers
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+1
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  rxdart: ^0.23.1
  font_awesome_flutter: ^8.5.0
  equatable: ^1.0.0
  google_sign_in: ^4.1.4
  firebase_auth: ^0.15.4
  graphql_flutter: ^3.0.0
  sqflite: ^1.2.2+1
  flutter_spinkit: ^4.1.1+1
  path_provider: ^1.6.5
  giffy_dialog: ^1.7.0
  flutter_svg: ^0.17.0
  flutter_paystack: ^1.0.3+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/gifs/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSansRegular.ttf
module:
  androidX: true